apiVersion: v1
kind: Service
metadata:
  name: ordersystem-order-service
  namespace: suguri
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: order