apiVersion: v1
# 자원의 종류를 명시
kind: Pod
metadata:
  name: nginx-pod
  namespace: suguri # 다같이 작업하기때문에 따로 실습중에는 네임스페이스 만든다.
  # labels는 service의 라우팅 대상이 되는 이름
  # service의 selector.app을 통해 매핑
  labels:
    app: my-nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80