apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  namespace: suguri
  labels:
    app: my-nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
--- # yml 특성 이걸로 한 파일 안에 다른 파일처럼 구분지을 수 있다.   할 수 있다.
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
  namespace: suguri
  labels:
    app: my-nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: suguri
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30192
  selector:
    app: my-nginx