apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  namespace: suguri
spec:
  replicas: 2
  #  아래 요소는 replicaset이 관리할 파드를 선택하기 위한 이름
  # template.metadata.labels의 이름과 일치해야함
  selector:
    matchLabels:
      app: my-nginx
  template:
  # 아래 labels.app부분은 service의 selector부분과 일치해야하고,
  # 위의 matchlabels와도 일치해야함.
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: suguri
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30192
  selector:
    app: my-nginx